### ISSUE TITLE
UI updates

### ISSUE THREAD

**Issue by digilou** [ddcornwall/nara-alaskana#1]
Once a lot of your functionality is worked out, I'd love to update your UI design / CSS that would meld branding from NARA and Alaska with a 2018 style.

Could I be added as a collaborator (in settings) to your project? Or would you rather I fork your repo and push a branch?

**Comment by ddcornwall** [comment]
So sorry I didn't see this before. I've added you as a collaborator, if you still have time for this. If not, no worries.

**Comment by digilou** [comment]
This will be fun! Yep, I'll start playing with it this weekend.
