### ISSUE TITLE
Create Bios page

### ISSUE THREAD

**Issue by digilou** [ddcornwall/nara-alaskana#11]
As mentioned in #4:
"... remove 'this is a personal project of Daniel Cornwall ...' from the bottom of pages. Let's also get rid of my transplanted navbar on the other pages. What do you think of creating a team page with short bios of us both? I don't want to take credit for your improved layout." 

- Create new page to hold short biographies of Daniel and Amy
- Update global navigation and footer navigation to accommodate for new collaboration

**Comment by digilou** [comment]
@ddcornwall Contributor page has been created, but needs information about you. I still want to think about what I'm going to say about myself.

**Comment by ddcornwall** [comment]
Added basic information about me. Merged into master branch since you created a pull request.
